### ISSUE TITLE
Tor Connection fail

### ISSUE THREAD

**Issue by curly60e** [pxsocs/warden_terminal#1]
Hi! 

I was testing node_warden.py on several OS like Mac/Raspbian/Ubuntu. One of them is a Tor Relay and I have the same problem.

![imagen](https://user-images.githubusercontent.com/55191248/102027470-0cd18580-3d83-11eb-978e-86eab1bd2780.png)

Is there something that I need to change or do some installation?
One of my other Ubuntu OS works perfectly and in MyNode too. Maybe modifying torrc?

**Comment by pxsocs** [comment]
A couple of users have reported that opening a Tor Browser fixes the issue

**Comment by curly60e** [comment]
Well not on my side. It's weird.

![image](https://user-images.githubusercontent.com/55191248/102114145-a26b2480-3e18-11eb-8892-fa24619bc345.png)

**Comment by clonmac** [comment]
I did some troubleshooting on my end as I was receiving the same error. I had tor locally as well as trying to get it working with my personal tor bridge node I have running and was getting the same error in both cases. I ended up finding out that what got it working for me was a missing 'pysocks' requirement in requirements.txt. Try adding pysocks into your requirements.txt before installing all the requirements or just install pysocks manually with pip and see if that works for you.

**Comment by curly60e** [comment]
Ok, this is solved on my Mac.

**Comment by pxsocs** [comment]
Update `requirements.txt` to include `pysocks` and `requests`. 
`click` was also a missing dependency and was included.

**Comment by curly60e** [comment]
Cool! Thanks!!
