### ISSUE TITLE
Feature Request - Portfolio Value

### ISSUE THREAD

**Issue by AnarchyNow** [pxsocs/warden_terminal#54]
I was playing around and thought about having a real-time BTC portfolio value in the header.  By adding a variable in the Config.ini called "Own", we can easily pull that quantity of BTC, multiply by the current price of BTC, and then show it in the header.  This would allow users to see their BTC portfolio value even if they do not have any Sats in their node's BTC wallet.  If there is ever trending added, this would be a cool point to watch.  Thoughts?

Config.ini:
[CURRENCIES]
primary_fx = 'USD'
fx_list = ['USD','EUR', 'GBP', 'CAD']
Own = 3.18688358

dashboard.py
        if small_display is True:
            from node_warden import load_config
            config = load_config(quiet=True)
            config = config['CURRENCIES']
            Own = config.getfloat("Own")
            primary_fx = ast.literal_eval(config.get('primary_fx'))
            Worth = float(btc_price * Own)
            txt = 'WARden Node Edition (Version: ' + version(
            ) +  ") | " f"${jformat(btc_price, 0)} {primary_fx}/BTC " + " | "  + f"Own: {Own} BTC | " + f"Net: ${jformat(Worth, 0)} {primary_fx}"
![Screen Shot 2021-07-30 at 3 05 06 PM](https://user-images.githubusercontent.com/88005449/127716154-f8047d89-3dc1-4fd8-ba85-c5f0fd633379.png)

**Comment by pxsocs** [comment]
Great suggestion and being implemented with a slight change. Given there's already too much info on the header, which makes it particularly crowded on smaller displays, the info will be displayed in 2 widgets - see below. 

It also complies with the <H> Hidden key press so when Hidden is True, info is not displayed. 

`config.ini` now has a new section:

```python
[PORTFOLIO]
position_btc = 1.00
```

![image](https://user-images.githubusercontent.com/40473443/127738127-4c460eb5-8b49-4852-9944-f9bb28187f9b.png)

![image](https://user-images.githubusercontent.com/40473443/127738237-a3268c11-50e7-494c-955a-111726b99762.png)

**Comment by pxsocs** [comment]
Implemented on the latest version: (https://github.com/pxsocs/warden_terminal/commit/ff292c89a16a0c4ca00d479c5700012d9a981585)
