### ISSUE TITLE
Feature Request - Specter on Muiti Widgets Screen

### ISSUE THREAD

**Issue by AnarchyNow** [pxsocs/warden_terminal#66]
Are there plans to add the Specter Server data to the Multi Widgets screen?

**Comment by pxsocs** [comment]
Yes. Considering including a config.ini section to customize multi-widget display. Coming soon.
But adding Specter on main multi-widget on next version.

**Comment by pxsocs** [comment]
Specter Status included in MultiWidget on version 0.0.570
