### ISSUE TITLE
Four values returned, tabs have three labels

### ISSUE THREAD

**Issue by AnarchyNow** [pxsocs/warden_terminal#79]
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/data.py#L832
![Screen Shot 2021-08-10 at 7 30 38 AM](https://user-images.githubusercontent.com/88005449/128885655-b01617b0-0e99-487e-ae88-4538016050ac.png)
![Screen Shot 2021-08-10 at 7 31 42 AM](https://user-images.githubusercontent.com/88005449/128885751-ddb04621-2ff3-4fef-a495-fce74bf090fa.png)

Any chance you could include a green text that counts how many blocks until taproot activation occurs (at 709632 i think) below the current block height?

**Comment by pxsocs** [comment]
Fixed on version 0.0.607
