### ISSUE TITLE
Wallet Ballance

### ISSUE THREAD

**Issue by AnarchyNow** [pxsocs/warden_terminal#80]
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/data.py#L1117

Although the variable "wallets" is defined earlier in the code, the addition of `wallets = rpc_connection.getbalances()` is needed for the confirmed and unconfirmed balances to return values.

**Comment by pxsocs** [comment]
This was a good catch. Thanks. Also fixed on next version.
