### ISSUE TITLE
Info text color change

### ISSUE THREAD

**Issue by AnarchyNow** [pxsocs/warden_terminal#81]
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/ansi_management.py#L26

Suggest changing the color from blue to white (or even green) since the blue font on black background has such little contrast it makes reading the text quite difficult.

**Comment by pxsocs** [comment]
Done. I've noticed a similar issue on some terminals. Made the change to bold green.
Fixed on next version.
