### ISSUE TITLE
Test_Tor site not working for non-tor connections

### ISSUE THREAD

**Issue by AnarchyNow** [pxsocs/warden_terminal#82]
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/connections.py#L20
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/connections.py#L38

This website is not cooperating with non-tor connections and is failing the "Test Tor" portion of the code.
I replaced the website with https://api.myip.com and 
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/connections.py#L44
changed to 
            if pre_proxy["ip"] != post_proxy["ip"]:
and 
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/data.py#L47
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/data.py#L49
needed to point to "ip" instead of "origin"

Is this issue only happening on my end or do you see it too?

Also:
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/connections.py#L41
should that be a "-" instead of "/" since you're saying this is a difference in ping response times?

**Comment by pxsocs** [comment]
I didn't see this issue on my end but tested the website provided above and works fine. Decided to make these changes as they may impact other users and work fine as a replacement.
For the `post_proxy_difference` variable, kept it as a multiple as the intention was to show that Tor was X times slower than no-Tor. Renamed the variable to `post_proxy_ratio`.
