### ISSUE TITLE
Hiding portfolio not working

### ISSUE THREAD

**Issue by AnarchyNow** [pxsocs/warden_terminal#84]
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/data.py#L580
https://github.com/pxsocs/warden_terminal/blob/a156a6f250f6d03c4f67d1a167b79a0b0c0f1755/data.py#L186
should be:
if config['MAIN'].getboolean('hide_private_info') is True:

**Comment by pxsocs** [comment]
Also a nice catch. Been struggling to see why the Tor screen was not showing IP :) 
Fixed on next version.

**Comment by AnarchyNow** [comment]
> Also a nice catch. Been struggling to see why the Tor screen was not showing IP :)
> Fixed on next version.

Happy to help!
